---
- name: create kafka group
  group: name=kafka system=true
- name: create kafka user
  user: name=kafka group=kafka system=true

- name: install numactl
  package:
    name: numactl
    state: present

- name: Install Kafka from remote
  unarchive:
    src: "{{ kafka_mirror }}/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: "/usr/local/lib/"
    remote_src: yes
    creates: "/usr/local/lib/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
  when: kafka_mirror != 'master'

- name: Install Kafka from master
  unarchive:
    src: "kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: "/usr/local/lib/"
  when: kafka_mirror == 'master'

- name: Link kafka
  file:
    src: "/usr/local/lib/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
    dest: "/usr/local/lib/kafka"
    state: link
  when: not ansible_check_mode
  notify: Restart Kafka

- name: Create tool links
  file:
    src: "/usr/local/lib/kafka/bin/{{ item }}.sh"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kafka-topics
    - kafka-configs
  when: not ansible_check_mode

- name: Create config directories
  file:
    path: "/etc/kafka"
    state: directory
    mode: 0755

- name: Create Filebeat config directories
  file:
    path: "/etc/kafka/filebeat"
    state: directory
    mode: 0755
  check_mode: no

- name: Create log directories
  file:
    path: "/var/log/kafka"
    state: directory
    owner: kafka
    group: kafka
    mode: 0755

- name: Create data directories
  file:
    path: "{{ kafka_log_dirs }}"
    state: directory
    owner: kafka
    group: kafka
    mode: 0755

- name: Kafka configuration
  template:
    src: "server.properties.j2"
    dest: /etc/kafka/server.properties
    mode: 0644
  notify: Restart Kafka

- name: Create Kafka SystemD unit configuration
  template:
    src: "kafka.service.j2"
    dest: /etc/systemd/system/kafka.service
    mode: 0644
  notify: Restart Kafka

- name: Kafka Filebeat specific configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/kafka/filebeat/humio.yml
    mode: 0644
    owner: root
    group: root


- name: Enable Kafka Service
  service:
    name: "kafka"
    enabled: yes
    state: started
