---
- group: name=kafka system=true
- user: name=kafka group=kafka system=true

- name: Install Kafka
  unarchive:
    src: "{{ kafka_mirror }}/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: /usr/lib/
    remote_src: yes

- name: Link kafka
  file:
    src: "/usr/lib/kafka_{{ kafka_scala_version }}-{{ kafka_version }}"
    dest: /usr/lib/kafka
    state: link
    owner: kafka
  notify: Restart Kafka

- name: Create config directories
  file:
    path: "/etc/kafka"
    state: directory

- name: Create log directories
  file:
    path: "/var/log/kafka"
    state: directory
    owner: kafka
    group: kafka

- name: Create data directories
  file:
    path: "/var/kafka/data"
    state: directory
    owner: kafka
    group: kafka

- name: Kafka configuration
  template:
    src: "server.properties.j2"
    dest: /etc/kafka/server.properties
  notify: Restart Kafka

- name: Create Kafka SystemD unit configuration
  template:
    src: "kafka.service.j2"
    dest: /etc/systemd/system/kafka.service
  notify: Restart Kafka

- name: Enable Kafka Service
  service:
    name: "kafka"
    enabled: yes
    state: started
